language: c
dist: focal
sudo: required
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq make gcc texinfo dejagnu

env:
  matrix:
  - TARGET=aarch64-linux-gnu
  - TARGET=aarch64-none-elf
  - TARGET=arm-linux-gnueabi
  - TARGET=arm-linux-gnueabihf
  - TARGET=arm-none-eabi

script: ./travis.sh

notifications:
  email:
    on_success: always
    recipients:
      - christophelyon@gmail.com
